import {
    createChessSquareWeightMatrix,
    createCrossWeightMatrix,
    createSquareWeightMatrix,
    createXWeightMatrix,
} from "./Weight.js"

export type Stage = {
    rows: number
    cols: number
    periods: number[]
    clicks: number[]
    weight: () => number[][]
    minStep: number
}

export const stages: Stage[] = [
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [0, 15],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 2,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [1, 3, 7],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 3,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [0, 6, 8, 13],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 4,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [7, 9, 12, 15, 8],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 5,
    },
    {
        rows: 5,
        cols: 5,
        periods: [
            [2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2],
            [2, 2, 2, 2, 2],
        ].flat(),
        clicks: [4, 6, 11, 22],
        weight: () => createSquareWeightMatrix(5, 5),
        minStep: 4,
    },

    {
        rows: 1,
        cols: 4,
        periods: [[3, 3, 3, 3]].flat(),
        clicks: [0, 3],
        weight: () => createSquareWeightMatrix(1, 4),
        minStep: 4,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
        ].flat(),
        clicks: [8, 9, 1, 10, 8, 1],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 6,
    },

    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
        ].flat(),
        clicks: [8, 3, 11, 14, 8],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 7,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
        ].flat(),
        clicks: [4, 9, 13, 7],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 8,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
            [3, 3, 3, 3],
        ].flat(),
        clicks: [0, 11, 5, 15, 7, 13],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: 12,
    },

    {
        rows: 1,
        cols: 4,
        periods: [[3, 3, 4, 4]].flat(),
        clicks: [0, 0, 2, 2, 1, 3],
        weight: () => createSquareWeightMatrix(1, 4),
        minStep: 4,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 2],
            [3, 3, 3, 2],
            [3, 3, 3, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [4, 6, 9, 2, 13, 6, 8],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [1, 2, 2, 1],
            [2, 3, 3, 2],
            [2, 3, 3, 2],
            [1, 2, 2, 1],
        ].flat(),
        clicks: [4, 6, 9, 2, 13, 6, 8],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 6],
            [2, 2, 2, 6],
            [3, 3, 3, 6],
            [3, 3, 3, 6],
        ].flat(),
        clicks: [13, 3, 11, 6, 0, 3, 9],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 4],
            [2, 2, 2, 4],
            [3, 3, 3, 4],
            [3, 3, 3, 4],
        ].flat(),
        clicks: [3, 1, 4, 15, 9, 2, 6, 5],
        weight: () => createSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },

    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [0, 15],
        weight: () => createCrossWeightMatrix(4, 4),
        minStep: 2,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 3, 3, 3],
            [3, 2, 2, 3],
            [3, 2, 2, 3],
            [3, 3, 3, 3],
        ].flat(),
        clicks: [0, 3, 4, 7, 9, 12, 3],
        weight: () => createCrossWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [1, 3, 3, 1],
            [3, 2, 2, 3],
            [3, 2, 2, 3],
            [1, 3, 3, 1],
        ].flat(),
        clicks: [0, 3, 4, 7, 9, 12, 3],
        weight: () => createCrossWeightMatrix(4, 4, [1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [1, 3, 3, 1],
            [3, 4, 4, 3],
            [3, 4, 4, 3],
            [1, 3, 3, 1],
        ].flat(),
        clicks: [0, 3, 4, 7, 9, 12, 3],
        weight: () => createCrossWeightMatrix(4, 4, [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [1, 3, 3, 1],
            [3, 4, 4, 3],
            [3, 4, 4, 3],
            [1, 3, 3, 1],
        ].flat(),
        clicks: [0, 3, 4, 7, 9, 12, 3],
        weight: () => createXWeightMatrix(4, 4, [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]),
        minStep: Infinity,
    },

    {
        rows: 1,
        cols: 4,
        periods: [[2, 2, 2, 2]].flat(),
        clicks: [1, 3],
        weight: () => createChessSquareWeightMatrix(1, 4),
        minStep: 2,
    },
    {
        rows: 1,
        cols: 4,
        periods: [[3, 2, 2, 3]].flat(),
        clicks: [0, 2],
        weight: () => createChessSquareWeightMatrix(1, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [2, 2, 2, 2],
            [2, Infinity, 2, 2],
            [2, 2, Infinity, 2],
            [2, 2, 2, 2],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 2, 2, 3],
            [2, Infinity, 2, 2],
            [2, 2, Infinity, 2],
            [3, 2, 2, 3],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 2, 4, 3],
            [2, Infinity, 4, 4],
            [4, 4, Infinity, 2],
            [3, 4, 2, 3],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4),
        minStep: Infinity,
    },

    {
        rows: 4,
        cols: 4,
        periods: [
            [1, 2, 3, 4],
            [2, Infinity, 6, 3],
            [3, 6, Infinity, 2],
            [4, 3, 2, 1],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4, [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 2, 4, 3],
            [2, Infinity, 4, 4],
            [4, 4, Infinity, 2],
            [3, 4, 2, 3],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4, [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 5, 4, 3],
            [5, Infinity, 4, 4],
            [4, 4, Infinity, 5],
            [3, 4, 5, 3],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4, [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [3, 5, 4, Infinity],
            [5, Infinity, 4, 4],
            [4, 4, Infinity, 5],
            [Infinity, 4, 5, 3],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4, [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]),
        minStep: Infinity,
    },
    {
        rows: 4,
        cols: 4,
        periods: [
            [Infinity, 3, 4, Infinity],
            [3, 5, 4, 4],
            [4, 4, 5, 3],
            [1, 4, 3, Infinity],
        ].flat(),
        clicks: [0, 2, 3, 5, 7, 11, 13],
        weight: () => createChessSquareWeightMatrix(4, 4, [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1]),
        minStep: Infinity,
    },
]
